In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from scipy import stats
from sklearn.datasets import load_iris

# 1.

In [2]:
iris = load_iris()

In [4]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df['sepal_width'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   sepal_width  
0            0  
1            0  
2            0  
3            0  
4            0

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

scaler = StandardScaler()
data_scaled = scaler.fit_transform(iris.data)

x_train, x_test, y_train, y_test = \
train_test_split(data_scaled, iris.target, test_size = 0.2, random_state=2020)


In [19]:
lr_clf = LogisticRegression()
lr_clf.fit(x_train, y_train)
lr_pred = lr_clf.predict(x_test)

mse = mean_squared_error(y_test, lr_pred)
rmse = np.sqrt(mse)

In [20]:
print(rmse)

0.4472135954999579


# 2.

In [30]:
df=pd.read_csv('./data/ThoraricSurgery.csv')

In [31]:
df.head(3)

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0    1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1    8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2   14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   

   0.9  62  0.10  
0    0  60     0  
1    0  66     1  
2    0  80     1

In [103]:
df_data = df.iloc[:,:-1]

In [104]:
df_data.head()

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0    1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1    8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2   14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   
3   17  2  2.21  1.88  0    0    1    0    0    0  12    0    0    0    1   
4   18  2  2.96  1.67  0    0    0    0    0    0  12    0    0    0    1   

   0.9  62  
0    0  60  
1    0  66  
2    0  80  
3    0  56  
4    0  61

In [105]:
df_target = df.iloc[:,-1]

df_target

0      0
1      1
2      1
3      0
4      0
      ..
464    0
465    0
466    0
467    1
468    0
Name: 0.10, Length: 469, dtype: int64

In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [128]:
x_train, x_test, y_train, y_test = train_test_split(df_data, df_target, 
                                                    test_size=0.2, random_state=2020, stratify=df_target, shuffle=True)

In [143]:
ts = LogisticRegression()
ts.fit(x_train, y_train)
pred_ts = ts.predict(x_test)
pred_proba = ts.predict_proba(x_test)[:, 1]

In [144]:
print(pred_proba)

[0.08289417 0.13732941 0.15961473 0.16612074 0.59556303 0.0367952
 0.0920998  0.10353244 0.04370162 0.12271299 0.07282689 0.11862518
 0.14469993 0.07931751 0.25060075 0.0755026  0.26914872 0.09308281
 0.12237905 0.11921843 0.13580627 0.17354933 0.12684611 0.09488401
 0.06457885 0.18421756 0.2749417  0.19205927 0.04822832 0.09728716
 0.35560181 0.10509869 0.21097589 0.20358779 0.1647173  0.19505985
 0.077455   0.202809   0.03164932 0.13029925 0.13540649 0.30001339
 0.05989604 0.01267975 0.08644853 0.05490734 0.13638194 0.14061196
 0.10074079 0.18561797 0.13810031 0.07148888 0.08223282 0.10941961
 0.14898508 0.54987641 0.0565324  0.05125634 0.1746396  0.11601619
 0.10101146 0.24472002 0.09153718 0.10716169 0.23002886 0.12533541
 0.20309023 0.15580175 0.11206497 0.19874096 0.1406655  0.11976583
 0.05522609 0.21590444 0.06903221 0.08673916 0.11209944 0.0777045
 0.09323271 0.08346583 0.11910325 0.15947506 0.1453463  0.09773497
 0.41390669 0.13646343 0.09901459 0.10569676 0.31794273 0.298041

In [145]:
print(accuracy_score(y_test, pred_ts))

0.851063829787234


In [146]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(x_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [147]:
pred_svr = svr.predict(x_test)

In [149]:
accuracy_score(y_test, pred_svr)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [142]:
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [151]:
pred_dt = dt.predict(x_test)
accuracy_score(y_test, pred_dt)

0.7021276595744681

# 3.

In [152]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [153]:
iris = load_iris()

In [155]:
columns = ['sepal_length', 'sepal_width', 'petal_lenght', 'petal_width']
irisDF = pd.DataFrame(iris.data, columns=columns)
irisDF['target']=iris.target

In [156]:
irisDF

sepal_length  sepal_width  petal_lenght  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [157]:
from sklearn.preprocessing import StandardScaler

iris_scaled = StandardScaler().fit_transform(irisDF.iloc[:, :-1])


In [158]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

pca.fit(iris_scaled)
iris_pca = pca.transform(iris_scaled)
print(iris_pca.shape)

(150, 2)


In [161]:
pca_columns = ['pca_component_1', 'pca_component_2']
irisDF_pca = pd.DataFrame(iris_pca, columns=pca_columns)
irisDF_pca['target']=iris.target

irisDF_pca.head()

pca_component_1  pca_component_2  target
0        -2.264703         0.480027       0
1        -2.080961        -0.674134       0
2        -2.364229        -0.341908       0
3        -2.299384        -0.597395       0
4        -2.389842         0.646835       0

In [162]:
from sklearn.preprocessing import scale
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [165]:
kmeans2 = KMeans(n_clusters=2, init='k-means++', max_iter=300, random_state=2020)

kmeans2.fit(irisDF_pca)
kmeans2.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [171]:
from sklearn.metrics import silhouette_samples, silhouette_score

score_samples = silhouette_samples(iris_pca, kmeans2.labels_)
irisDF_pca['silhouette_coeff'] = score_samples
average_score2 = silhouette_score(iris.data, kmeans2.labels_)

In [172]:
print('붓꽃 데이터 세트 Silhouette Analysis Score:{0:.3f}'.format(average_score2))

붓꽃 데이터 세트 Silhouette Analysis Score:0.687


In [166]:
kmeans3 = KMeans(n_clusters=3, init='k-means++', max_iter=300, random_state=2020)

kmeans3.fit(irisDF_pca)
kmeans3.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1])

In [175]:
from sklearn.metrics import silhouette_samples, silhouette_score

score_samples = silhouette_samples(iris_pca, kmeans3.labels_)
irisDF_pca['silhouette_coeff'] = score_samples
average_score3 = silhouette_score(iris.data, kmeans3.labels_)

In [176]:
print('붓꽃 데이터 세트 Silhouette Analysis Score:{0:.3f}'.format(average_score3))

붓꽃 데이터 세트 Silhouette Analysis Score:0.502


In [167]:
kmeans4 = KMeans(n_clusters=4, init='k-means++', max_iter=300, random_state=2020)

kmeans4.fit(irisDF_pca)
kmeans4.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 3, 0, 0, 0, 3, 0, 3, 3, 0, 3, 0, 3, 0,
       0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 3,
       0, 3, 3, 0, 3, 3, 3, 0, 0, 0, 3, 3, 2, 0, 2, 0, 2, 2, 3, 2, 0, 2,
       2, 0, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [177]:
from sklearn.metrics import silhouette_samples, silhouette_score

score_samples = silhouette_samples(iris_pca, kmeans4.labels_)
irisDF_pca['silhouette_coeff'] = score_samples
average_score4 = silhouette_score(iris.data, kmeans4.labels_)

In [178]:
print('붓꽃 데이터 세트 Silhouette Analysis Score:{0:.3f}'.format(average_score4))

붓꽃 데이터 세트 Silhouette Analysis Score:0.460


# 4.

In [190]:
md = pd.read_csv('./data/midway.tsv', sep = "\t", quoting=3)
md.head()

Unnamed: 0  평점                일시  \
0           0   9  2019.12.31 09:48   
1           1  10  2019.12.31 10:41   
2           2  10  2019.12.31 09:38   
3           3  10  2019.12.31 09:14   
4           4  10  2019.12.31 19:58   

                                                 감상평  
0                         미드웨이가 재밌으면 추천 백두산이 재밌으면 비추  
1                          저 해전이 있었기에 우리나라 광복도 가능 했음  
2                       백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라  
3      방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.  
4  교과서에는 미드웨이 해전에서 미국이 승리했다고 한 줄로 서술되어 있지만 단순히 한 ...

In [191]:
md['평점']

0        9
1       10
2       10
3       10
4       10
        ..
4820     1
4821     2
4822     2
4823     4
4824     1
Name: 평점, Length: 4825, dtype: int64

In [255]:
from konlpy.tag import Okt

okt = Okt()
class_md = md['평점']
feature_md = md.drop(['Unnamed: 0', '평점', '일시'], axis=1, inplace=False)

In [256]:
feature_md

감상평
0                            미드웨이가 재밌으면 추천 백두산이 재밌으면 비추
1                             저 해전이 있었기에 우리나라 광복도 가능 했음
2                          백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라
3         방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.
4     교과서에는 미드웨이 해전에서 미국이 승리했다고 한 줄로 서술되어 있지만 단순히 한 ...
...                                                 ...
4820  대만에서 10월31일 개봉했었는데.성공못했음. 미국에서도 성적이 별로구..그이유가 ...
4821  아니 이게 재밌다는 사람은 뭐야?;그냥 국뽕->미국뽕 이 차이밖에 없는데 이 영화가...
4822                  시간이 아까워요. 엉성한 그래서 감동도 교훈도 없는...ㅉㅉ
4823                   진주만보다 낫다고해서봤는데대실망...천조국,왜놈들 국뽕영화
4824  우리는 왜 이런 영화 못만드냐? 싸구려 좌파 찌라시 백x산이나 대놓고 친북사상 반일...

[4825 rows x 1 columns]

In [259]:
x_train.shape, x_test.shape

((3860, 1), (965, 1))

In [260]:
x_train, x_test, y_train, y_test = train_test_split(feature_md, class_md, test_size=0.2,
                                                   random_state=2020)